"""data protection: access log, retention, erasure

Revision ID: 258a835bf5d9
Revises: 64b0afb5a8f6
Create Date: 2026-09-20 15:58:31.416910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '258a835bf5d9'
down_revision = '64b0afb5a8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('password_resets',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_ip', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_password_resets_token_hash'), ['token_hash'], unique=True)
        batch_op.create_index(batch_op.f('ix_password_resets_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_reset_user_used', ['user_id', 'used_at'], unique=False)

    op.create_table('access_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_role', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.create_index('ix_access_actor_time', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index('ix_access_complaint_time', ['complaint_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_access_logs_institution_id'), ['institution_id'], unique=False)

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('retention_months', sa.Integer(), nullable=False))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('erased_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('erased_at')

    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_column('retention_months')

    with op.batch_alter_table('access_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_access_logs_institution_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_access_logs_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_access_logs_actor_id'))
        batch_op.drop_index('ix_access_complaint_time')
        batch_op.drop_index('ix_access_actor_time')

    op.drop_table('access_logs')
    with op.batch_alter_table('password_resets', schema=None) as batch_op:
        batch_op.drop_index('ix_reset_user_used')
        batch_op.drop_index(batch_op.f('ix_password_resets_user_id'))
        batch_op.drop_index(batch_op.f('ix_password_resets_token_hash'))

    op.drop_table('password_resets')
    # ### end Alembic commands ###
