"""initial schema

Revision ID: 64b0afb5a8f6
Revises: 
Create Date: 2026-09-18 07:30:13.455055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b0afb5a8f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institutions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=60), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('brand_hue', sa.Integer(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('default_sla_hours', sa.Integer(), nullable=False),
    sa.Column('acknowledge_sla_hours', sa.Integer(), nullable=False),
    sa.Column('working_hours_start', sa.Integer(), nullable=False),
    sa.Column('working_hours_end', sa.Integer(), nullable=False),
    sa.Column('allow_anonymous', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('ticket_sequence', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institutions_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_institutions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_institutions_slug'), ['slug'], unique=True)

    op.create_table('departments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=400), nullable=True),
    sa.Column('sla_hours', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'slug', name='uq_department_slug_per_institution')
    )
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_departments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_departments_institution_id'), ['institution_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('matric_number', sa.String(length=40), nullable=True),
    sa.Column('faculty', sa.String(length=100), nullable=True),
    sa.Column('department_name', sa.String(length=120), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'email', name='uq_user_email_per_institution'),
    sa.UniqueConstraint('institution_id', 'matric_number', name='uq_user_matric_per_institution')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_user_institution_role', ['institution_id', 'role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_matric_number'), ['matric_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('complaints',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('ticket_number', sa.String(length=20), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('department_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('is_anonymous', sa.Boolean(), nullable=False),
    sa.Column('acknowledge_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolve_due_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('decline_reason', sa.Text(), nullable=True),
    sa.Column('satisfaction_rating', sa.Integer(), nullable=True),
    sa.Column('satisfaction_comment', sa.String(length=500), nullable=True),
    sa.Column('response_count', sa.Integer(), nullable=False),
    sa.Column('escalated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reminder_sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'ticket_number', name='uq_ticket_per_institution')
    )
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.create_index('ix_complaint_assignee', ['institution_id', 'assigned_to_id'], unique=False)
        batch_op.create_index('ix_complaint_institution_created', ['institution_id', 'created_at'], unique=False)
        batch_op.create_index('ix_complaint_institution_status', ['institution_id', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_assigned_to_id'), ['assigned_to_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_department_id'), ['department_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_escalated_at'), ['escalated_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_resolve_due_at'), ['resolve_due_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_student_id'), ['student_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaints_ticket_number'), ['ticket_number'], unique=False)

    op.create_table('complaint_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('from_value', sa.String(length=120), nullable=True),
    sa.Column('to_value', sa.String(length=120), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('complaint_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_complaint_events_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_complaint_events_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index('ix_event_complaint_created', ['complaint_id', 'created_at'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notification_user_read', ['user_id', 'is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    op.create_table('outbound_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('complaint_id', sa.String(length=36), nullable=True),
    sa.Column('channel', sa.String(length=10), nullable=False),
    sa.Column('recipient', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbound_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbound_messages_status'), ['status'], unique=False)
        batch_op.create_index('ix_outbound_status_created', ['status', 'created_at'], unique=False)

    op.create_table('responses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('author_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.create_index('ix_response_complaint_created', ['complaint_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_responses_institution_id'), ['institution_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('institution_id', sa.String(length=36), nullable=False),
    sa.Column('complaint_id', sa.String(length=36), nullable=False),
    sa.Column('response_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_id', sa.String(length=36), nullable=True),
    sa.Column('original_name', sa.String(length=255), nullable=False),
    sa.Column('stored_name', sa.String(length=120), nullable=False),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=False),
    sa.Column('thumbnail_name', sa.String(length=120), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['institution_id'], ['institutions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['response_id'], ['responses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stored_name')
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index('ix_attachment_complaint', ['complaint_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_complaint_id'), ['complaint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_attachments_institution_id'), ['institution_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_attachments_created_at'))
        batch_op.drop_index(batch_op.f('ix_attachments_complaint_id'))
        batch_op.drop_index('ix_attachment_complaint')

    op.drop_table('attachments')
    with op.batch_alter_table('responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_responses_institution_id'))
        batch_op.drop_index(batch_op.f('ix_responses_created_at'))
        batch_op.drop_index(batch_op.f('ix_responses_complaint_id'))
        batch_op.drop_index(batch_op.f('ix_responses_author_id'))
        batch_op.drop_index('ix_response_complaint_created')

    op.drop_table('responses')
    with op.batch_alter_table('outbound_messages', schema=None) as batch_op:
        batch_op.drop_index('ix_outbound_status_created')
        batch_op.drop_index(batch_op.f('ix_outbound_messages_status'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_institution_id'))
        batch_op.drop_index(batch_op.f('ix_outbound_messages_created_at'))

    op.drop_table('outbound_messages')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_institution_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))
        batch_op.drop_index('ix_notification_user_read')

    op.drop_table('notifications')
    with op.batch_alter_table('complaint_events', schema=None) as batch_op:
        batch_op.drop_index('ix_event_complaint_created')
        batch_op.drop_index(batch_op.f('ix_complaint_events_institution_id'))
        batch_op.drop_index(batch_op.f('ix_complaint_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaint_events_complaint_id'))

    op.drop_table('complaint_events')
    with op.batch_alter_table('complaints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_complaints_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_complaints_student_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_status'))
        batch_op.drop_index(batch_op.f('ix_complaints_resolve_due_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_priority'))
        batch_op.drop_index(batch_op.f('ix_complaints_institution_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_escalated_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_department_id'))
        batch_op.drop_index(batch_op.f('ix_complaints_created_at'))
        batch_op.drop_index(batch_op.f('ix_complaints_category'))
        batch_op.drop_index(batch_op.f('ix_complaints_assigned_to_id'))
        batch_op.drop_index('ix_complaint_institution_status')
        batch_op.drop_index('ix_complaint_institution_created')
        batch_op.drop_index('ix_complaint_assignee')

    op.drop_table('complaints')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_matric_number'))
        batch_op.drop_index(batch_op.f('ix_users_institution_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_department_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))
        batch_op.drop_index('ix_user_institution_role')

    op.drop_table('users')
    with op.batch_alter_table('departments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_departments_institution_id'))
        batch_op.drop_index(batch_op.f('ix_departments_created_at'))

    op.drop_table('departments')
    with op.batch_alter_table('institutions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institutions_slug'))
        batch_op.drop_index(batch_op.f('ix_institutions_created_at'))
        batch_op.drop_index(batch_op.f('ix_institutions_code'))

    op.drop_table('institutions')
    # ### end Alembic commands ###
